devices:
  - name: "CORE-SW1"
    host: "198.18.133.101"
    username: "admin"
    password: "cisco"
    device_type: "cisco_ios"
    port: 22
    timeout: 30

  - name: "CORE-SW2"
    host: "198.18.133.202"
    username: "admin"
    password: "cisco"
    device_type: "cisco_ios"
    port: 22
    timeout: 30
