devices:
  - name: "CORE-SW1"
    host: "198.18.133.101"
    username: "admin"
    password: "C1sco12345"
    device_type: "cisco_ios"
    port: 22
    timeout: 30

  - name: "CORE-SW2"
    host: "198.18.133.202"
    username: "admin"
    password: "C1sco12345"
    device_type: "cisco_ios"
    port: 22
    timeout: 30

  - name: "DESKTOP-1"
    host: "10.10.10.11"
    username: "cisco"
    password: "cisco"
    device_type: "generic_os"
    port: 22
    timeout: 30
